// Curated SAT vocabulary — high-frequency words grouped into study decks.
// Used by the /vocabulary flashcard + quiz feature. Pure data, no DB needed;
// per-user progress is tracked client-side in localStorage.

export interface VocabWord {
  id: string; // stable slug, used as the localStorage progress key
  word: string;
  pos: string; // part of speech
  definition: string;
  example: string;
  synonyms?: string[];
}

export interface VocabDeck {
  id: string;
  title: string;
  description: string;
  words: VocabWord[];
}

export const VOCAB_DECKS: VocabDeck[] = [
  {
    id: "essential",
    title: "Essential SAT Words",
    description: "High-frequency words that show up across Reading & Writing passages.",
    words: [
      {
        id: "ambiguous",
        word: "ambiguous",
        pos: "adjective",
        definition: "open to more than one interpretation; not clear or decided.",
        example: "The poem's ambiguous ending left readers debating its meaning.",
        synonyms: ["unclear", "vague", "equivocal"],
      },
      {
        id: "candid",
        word: "candid",
        pos: "adjective",
        definition: "truthful and straightforward; frank.",
        example: "In a candid interview, the author admitted her early drafts were weak.",
        synonyms: ["frank", "honest", "open"],
      },
      {
        id: "concise",
        word: "concise",
        pos: "adjective",
        definition: "giving a lot of information clearly and in a few words.",
        example: "The editor praised the report for being concise yet thorough.",
        synonyms: ["succinct", "brief", "terse"],
      },
      {
        id: "diligent",
        word: "diligent",
        pos: "adjective",
        definition: "showing care and conscientious effort in one's work.",
        example: "Her diligent note-taking paid off during final exams.",
        synonyms: ["industrious", "assiduous", "hardworking"],
      },
      {
        id: "novel",
        word: "novel",
        pos: "adjective",
        definition: "new or unusual in an interesting way.",
        example: "The startup proposed a novel approach to recycling plastic.",
        synonyms: ["innovative", "original", "fresh"],
      },
      {
        id: "prudent",
        word: "prudent",
        pos: "adjective",
        definition: "acting with care and thought for the future.",
        example: "It was prudent to save part of every paycheck.",
        synonyms: ["sensible", "judicious", "cautious"],
      },
      {
        id: "skeptical",
        word: "skeptical",
        pos: "adjective",
        definition: "not easily convinced; having doubts or reservations.",
        example: "Scientists were skeptical of the bold claim until it was replicated.",
        synonyms: ["doubtful", "dubious", "wary"],
      },
      {
        id: "trivial",
        word: "trivial",
        pos: "adjective",
        definition: "of little value or importance.",
        example: "Don't waste time arguing over trivial details.",
        synonyms: ["minor", "insignificant", "petty"],
      },
      {
        id: "viable",
        word: "viable",
        pos: "adjective",
        definition: "capable of working successfully; feasible.",
        example: "Solar power became a viable alternative as costs dropped.",
        synonyms: ["feasible", "workable", "practical"],
      },
      {
        id: "scrutinize",
        word: "scrutinize",
        pos: "verb",
        definition: "to examine or inspect closely and thoroughly.",
        example: "Reviewers scrutinized the data for any sign of error.",
        synonyms: ["examine", "inspect", "scrutinise"],
      },
      {
        id: "advocate",
        word: "advocate",
        pos: "verb",
        definition: "to publicly recommend or support.",
        example: "She advocates for stronger protections for public libraries.",
        synonyms: ["champion", "endorse", "support"],
      },
      {
        id: "undermine",
        word: "undermine",
        pos: "verb",
        definition: "to weaken or damage, often gradually or secretly.",
        example: "Spreading rumors can undermine a team's trust.",
        synonyms: ["weaken", "erode", "sabotage"],
      },
    ],
  },
  {
    id: "argument",
    title: "Academic & Argument",
    description: "Words for analyzing claims, evidence, and reasoning in arguments.",
    words: [
      {
        id: "assertion",
        word: "assertion",
        pos: "noun",
        definition: "a confident and forceful statement of fact or belief.",
        example: "The author's central assertion is that cities should ban cars downtown.",
        synonyms: ["claim", "declaration", "contention"],
      },
      {
        id: "credible",
        word: "credible",
        pos: "adjective",
        definition: "able to be believed; convincing.",
        example: "A credible source cited peer-reviewed studies.",
        synonyms: ["believable", "plausible", "reliable"],
      },
      {
        id: "empirical",
        word: "empirical",
        pos: "adjective",
        definition: "based on observation or experiment rather than theory.",
        example: "The hypothesis was confirmed by empirical evidence.",
        synonyms: ["observed", "experimental", "factual"],
      },
      {
        id: "refute",
        word: "refute",
        pos: "verb",
        definition: "to prove a statement or theory to be wrong.",
        example: "New fossils refuted the earlier timeline of migration.",
        synonyms: ["disprove", "rebut", "debunk"],
      },
      {
        id: "substantiate",
        word: "substantiate",
        pos: "verb",
        definition: "to provide evidence to support or prove the truth of.",
        example: "The lawyer could not substantiate the accusation.",
        synonyms: ["prove", "verify", "corroborate"],
      },
      {
        id: "concede",
        word: "concede",
        pos: "verb",
        definition: "to admit that something is true, often reluctantly.",
        example: "The critic conceded that the film had a few strong scenes.",
        synonyms: ["acknowledge", "admit", "grant"],
      },
      {
        id: "plausible",
        word: "plausible",
        pos: "adjective",
        definition: "seeming reasonable or probable.",
        example: "It's a plausible explanation, but it still needs testing.",
        synonyms: ["believable", "reasonable", "credible"],
      },
      {
        id: "coherent",
        word: "coherent",
        pos: "adjective",
        definition: "logical and consistent; clearly connected.",
        example: "A coherent essay leads the reader smoothly from point to point.",
        synonyms: ["logical", "consistent", "lucid"],
      },
      {
        id: "nuance",
        word: "nuance",
        pos: "noun",
        definition: "a subtle difference in meaning, expression, or tone.",
        example: "The translation lost the nuance of the original phrase.",
        synonyms: ["subtlety", "shade", "distinction"],
      },
      {
        id: "objective",
        word: "objective",
        pos: "adjective",
        definition: "not influenced by personal feelings; based on facts.",
        example: "A good reporter strives to be objective.",
        synonyms: ["impartial", "unbiased", "neutral"],
      },
      {
        id: "rhetoric",
        word: "rhetoric",
        pos: "noun",
        definition: "the art of effective or persuasive speaking and writing.",
        example: "The speech was praised for its powerful rhetoric.",
        synonyms: ["oratory", "eloquence", "persuasion"],
      },
      {
        id: "implication",
        word: "implication",
        pos: "noun",
        definition: "a conclusion or meaning that is suggested but not stated.",
        example: "The implication of the study is that sleep affects memory.",
        synonyms: ["suggestion", "inference", "consequence"],
      },
    ],
  },
  {
    id: "tone",
    title: "Tone & Attitude",
    description: "Words that describe an author's tone — key for Reading questions.",
    words: [
      {
        id: "indifferent",
        word: "indifferent",
        pos: "adjective",
        definition: "having no particular interest or concern; apathetic.",
        example: "He was indifferent to the outcome of the game.",
        synonyms: ["apathetic", "unconcerned", "detached"],
      },
      {
        id: "ardent",
        word: "ardent",
        pos: "adjective",
        definition: "very enthusiastic or passionate.",
        example: "She is an ardent supporter of ocean conservation.",
        synonyms: ["passionate", "fervent", "zealous"],
      },
      {
        id: "somber",
        word: "somber",
        pos: "adjective",
        definition: "dark or dull in tone; gloomy and serious.",
        example: "The memorial had a somber, reflective mood.",
        synonyms: ["gloomy", "grave", "solemn"],
      },
      {
        id: "sarcastic",
        word: "sarcastic",
        pos: "adjective",
        definition: "using irony to mock or convey contempt.",
        example: "\"Nice job,\" she said in a sarcastic tone after the spill.",
        synonyms: ["mocking", "sardonic", "caustic"],
      },
      {
        id: "nostalgic",
        word: "nostalgic",
        pos: "adjective",
        definition: "longing affectionately for the past.",
        example: "The song made him nostalgic for his childhood summers.",
        synonyms: ["wistful", "sentimental", "yearning"],
      },
      {
        id: "cynical",
        word: "cynical",
        pos: "adjective",
        definition: "believing that people are motivated by self-interest; distrustful.",
        example: "Years in politics had made her cynical about promises.",
        synonyms: ["distrustful", "pessimistic", "jaded"],
      },
      {
        id: "reverent",
        word: "reverent",
        pos: "adjective",
        definition: "feeling or showing deep respect.",
        example: "The crowd fell into a reverent silence.",
        synonyms: ["respectful", "awed", "deferential"],
      },
      {
        id: "ambivalent",
        word: "ambivalent",
        pos: "adjective",
        definition: "having mixed or contradictory feelings about something.",
        example: "She felt ambivalent about moving to a new city.",
        synonyms: ["conflicted", "torn", "uncertain"],
      },
      {
        id: "earnest",
        word: "earnest",
        pos: "adjective",
        definition: "sincere and serious in intention.",
        example: "He made an earnest effort to apologize.",
        synonyms: ["sincere", "heartfelt", "serious"],
      },
      {
        id: "condescending",
        word: "condescending",
        pos: "adjective",
        definition: "having a superior, patronizing attitude.",
        example: "His condescending tone annoyed his classmates.",
        synonyms: ["patronizing", "haughty", "superior"],
      },
      {
        id: "wary",
        word: "wary",
        pos: "adjective",
        definition: "cautious about possible dangers or problems.",
        example: "Investors were wary of the unproven technology.",
        synonyms: ["cautious", "guarded", "careful"],
      },
      {
        id: "optimistic",
        word: "optimistic",
        pos: "adjective",
        definition: "hopeful and confident about the future.",
        example: "Despite setbacks, the team remained optimistic.",
        synonyms: ["hopeful", "positive", "upbeat"],
      },
    ],
  },
  {
    id: "advanced",
    title: "Advanced & High-Frequency",
    description: "Tougher words that separate top scorers on the hardest questions.",
    words: [
      {
        id: "pragmatic",
        word: "pragmatic",
        pos: "adjective",
        definition: "dealing with things practically rather than ideally.",
        example: "She took a pragmatic approach, fixing what could be fixed.",
        synonyms: ["practical", "realistic", "sensible"],
      },
      {
        id: "ephemeral",
        word: "ephemeral",
        pos: "adjective",
        definition: "lasting for a very short time.",
        example: "Fame can be ephemeral, fading as quickly as it arrives.",
        synonyms: ["fleeting", "transient", "short-lived"],
      },
      {
        id: "meticulous",
        word: "meticulous",
        pos: "adjective",
        definition: "showing great attention to detail; very careful.",
        example: "The watchmaker was meticulous about every gear.",
        synonyms: ["thorough", "precise", "fastidious"],
      },
      {
        id: "ubiquitous",
        word: "ubiquitous",
        pos: "adjective",
        definition: "present, appearing, or found everywhere.",
        example: "Smartphones have become ubiquitous in daily life.",
        synonyms: ["omnipresent", "pervasive", "widespread"],
      },
      {
        id: "tenacious",
        word: "tenacious",
        pos: "adjective",
        definition: "holding firmly to a goal; persistent.",
        example: "Her tenacious effort finally won the scholarship.",
        synonyms: ["persistent", "determined", "dogged"],
      },
      {
        id: "innocuous",
        word: "innocuous",
        pos: "adjective",
        definition: "not harmful or offensive.",
        example: "The comment seemed innocuous, but it sparked a debate.",
        synonyms: ["harmless", "benign", "inoffensive"],
      },
      {
        id: "superfluous",
        word: "superfluous",
        pos: "adjective",
        definition: "more than is needed or useful; unnecessary.",
        example: "The editor cut superfluous adjectives from the draft.",
        synonyms: ["excessive", "redundant", "needless"],
      },
      {
        id: "austere",
        word: "austere",
        pos: "adjective",
        definition: "severe or strict in manner; plain and without comfort.",
        example: "The monks lived an austere life of study and silence.",
        synonyms: ["stern", "spartan", "plain"],
      },
      {
        id: "vindicate",
        word: "vindicate",
        pos: "verb",
        definition: "to clear of blame or prove right.",
        example: "New evidence vindicated the wrongly accused man.",
        synonyms: ["exonerate", "absolve", "justify"],
      },
      {
        id: "mitigate",
        word: "mitigate",
        pos: "verb",
        definition: "to make less severe, serious, or painful.",
        example: "Planting trees can mitigate the effects of heat in cities.",
        synonyms: ["alleviate", "lessen", "ease"],
      },
      {
        id: "exacerbate",
        word: "exacerbate",
        pos: "verb",
        definition: "to make a problem or situation worse.",
        example: "Ignoring the leak only exacerbated the damage.",
        synonyms: ["worsen", "aggravate", "intensify"],
      },
      {
        id: "paradox",
        word: "paradox",
        pos: "noun",
        definition: "a statement that seems contradictory but may be true.",
        example: "It's a paradox that spending money can sometimes save it.",
        synonyms: ["contradiction", "puzzle", "irony"],
      },
    ],
  },
  {
    id: "science",
    title: "Science & Discovery",
    description: "Words common in science passages — research, data, and natural processes.",
    words: [
      {
        id: "hypothesis",
        word: "hypothesis",
        pos: "noun",
        definition: "a proposed explanation made on limited evidence as a starting point for further investigation.",
        example: "Their hypothesis was that warmer water sped up the reaction.",
        synonyms: ["theory", "supposition", "conjecture"],
      },
      {
        id: "phenomenon",
        word: "phenomenon",
        pos: "noun",
        definition: "an observable fact or event, especially one whose cause is in question.",
        example: "The northern lights are a striking natural phenomenon.",
        synonyms: ["occurrence", "event", "marvel"],
      },
      {
        id: "catalyst",
        word: "catalyst",
        pos: "noun",
        definition: "something that speeds up a reaction or causes change.",
        example: "The discovery acted as a catalyst for further research.",
        synonyms: ["stimulus", "spur", "trigger"],
      },
      {
        id: "anomaly",
        word: "anomaly",
        pos: "noun",
        definition: "something that deviates from what is standard or expected.",
        example: "The sensor reading was an anomaly the team could not explain.",
        synonyms: ["irregularity", "deviation", "aberration"],
      },
      {
        id: "correlation",
        word: "correlation",
        pos: "noun",
        definition: "a relationship in which two things tend to change together.",
        example: "There is a correlation between sleep and test performance.",
        synonyms: ["link", "association", "connection"],
      },
      {
        id: "finite",
        word: "finite",
        pos: "adjective",
        definition: "having limits or bounds; not endless.",
        example: "Fossil fuels are a finite resource.",
        synonyms: ["limited", "bounded", "measurable"],
      },
      {
        id: "dynamic",
        word: "dynamic",
        pos: "adjective",
        definition: "characterized by constant change or activity.",
        example: "Ecosystems are dynamic, shifting with the seasons.",
        synonyms: ["changing", "active", "fluid"],
      },
      {
        id: "synthesize",
        word: "synthesize",
        pos: "verb",
        definition: "to combine separate elements into a connected whole.",
        example: "Plants synthesize sugars from sunlight and water.",
        synonyms: ["combine", "integrate", "fuse"],
      },
      {
        id: "deduce",
        word: "deduce",
        pos: "verb",
        definition: "to reach a conclusion by reasoning from known facts.",
        example: "From the footprints, she deduced the animal's size.",
        synonyms: ["infer", "conclude", "reason"],
      },
      {
        id: "negligible",
        word: "negligible",
        pos: "adjective",
        definition: "so small or unimportant as to be not worth considering.",
        example: "The change in temperature was negligible.",
        synonyms: ["insignificant", "tiny", "minimal"],
      },
      {
        id: "quantify",
        word: "quantify",
        pos: "verb",
        definition: "to express or measure as a quantity.",
        example: "It is hard to quantify the value of clean air.",
        synonyms: ["measure", "count", "gauge"],
      },
      {
        id: "robust",
        word: "robust",
        pos: "adjective",
        definition: "strong and unlikely to fail; sturdy.",
        example: "The study's robust data convinced skeptics.",
        synonyms: ["strong", "sturdy", "resilient"],
      },
    ],
  },
  {
    id: "society",
    title: "Society & Power",
    description: "Words about people, institutions, history, and how power works.",
    words: [
      {
        id: "autonomy",
        word: "autonomy",
        pos: "noun",
        definition: "the right or condition of self-government; independence.",
        example: "The region was granted greater autonomy.",
        synonyms: ["independence", "self-rule", "freedom"],
      },
      {
        id: "egalitarian",
        word: "egalitarian",
        pos: "adjective",
        definition: "believing in or based on the equality of all people.",
        example: "The movement promoted egalitarian values.",
        synonyms: ["equal", "fair", "democratic"],
      },
      {
        id: "hierarchy",
        word: "hierarchy",
        pos: "noun",
        definition: "a system in which people or things are ranked one above another.",
        example: "The company has a strict management hierarchy.",
        synonyms: ["ranking", "order", "pecking order"],
      },
      {
        id: "ideology",
        word: "ideology",
        pos: "noun",
        definition: "a system of ideas and ideals, especially political or economic.",
        example: "The two parties were divided by ideology.",
        synonyms: ["beliefs", "doctrine", "philosophy"],
      },
      {
        id: "dissent",
        word: "dissent",
        pos: "noun",
        definition: "the holding or expression of opinions at variance with those held by most.",
        example: "The judge wrote a sharp dissent.",
        synonyms: ["disagreement", "objection", "opposition"],
      },
      {
        id: "reform",
        word: "reform",
        pos: "noun",
        definition: "a change made to improve a system, law, or institution.",
        example: "Voters demanded reform of the tax code.",
        synonyms: ["improvement", "change", "overhaul"],
      },
      {
        id: "oppress",
        word: "oppress",
        pos: "verb",
        definition: "to keep down by unjust use of power.",
        example: "The regime oppressed anyone who spoke out.",
        synonyms: ["subjugate", "tyrannize", "repress"],
      },
      {
        id: "prevalent",
        word: "prevalent",
        pos: "adjective",
        definition: "widespread in a particular area or at a particular time.",
        example: "The belief was prevalent in the nineteenth century.",
        synonyms: ["widespread", "common", "rife"],
      },
      {
        id: "marginalize",
        word: "marginalize",
        pos: "verb",
        definition: "to treat a person or group as insignificant or peripheral.",
        example: "The policy marginalized rural communities.",
        synonyms: ["sideline", "exclude", "isolate"],
      },
      {
        id: "consensus",
        word: "consensus",
        pos: "noun",
        definition: "general agreement among a group.",
        example: "The committee reached a consensus after hours of debate.",
        synonyms: ["agreement", "accord", "unanimity"],
      },
      {
        id: "legitimate",
        word: "legitimate",
        pos: "adjective",
        definition: "conforming to the law or to accepted rules; justifiable.",
        example: "She raised a legitimate concern about the budget.",
        synonyms: ["valid", "lawful", "rightful"],
      },
      {
        id: "civic",
        word: "civic",
        pos: "adjective",
        definition: "relating to a city, citizens, or community affairs.",
        example: "Voting is a basic civic duty.",
        synonyms: ["public", "communal", "municipal"],
      },
    ],
  },
  {
    id: "verbs",
    title: "Power Verbs",
    description: "Strong action verbs that sharpen writing and show up in answer choices.",
    words: [
      {
        id: "alleviate",
        word: "alleviate",
        pos: "verb",
        definition: "to make suffering or a problem less severe.",
        example: "The medicine alleviated her headache.",
        synonyms: ["ease", "relieve", "lessen"],
      },
      {
        id: "augment",
        word: "augment",
        pos: "verb",
        definition: "to make something greater by adding to it.",
        example: "She augmented her income with a second job.",
        synonyms: ["increase", "boost", "supplement"],
      },
      {
        id: "compel",
        word: "compel",
        pos: "verb",
        definition: "to force or strongly urge someone to do something.",
        example: "Bad weather compelled them to cancel the trip.",
        synonyms: ["force", "oblige", "drive"],
      },
      {
        id: "curtail",
        word: "curtail",
        pos: "verb",
        definition: "to reduce or restrict something.",
        example: "The city curtailed water use during the drought.",
        synonyms: ["cut", "restrict", "trim"],
      },
      {
        id: "diminish",
        word: "diminish",
        pos: "verb",
        definition: "to make or become less.",
        example: "His enthusiasm diminished over time.",
        synonyms: ["decrease", "lessen", "wane"],
      },
      {
        id: "endure",
        word: "endure",
        pos: "verb",
        definition: "to suffer something painful patiently; to last.",
        example: "The bridge has endured for two centuries.",
        synonyms: ["withstand", "last", "persist"],
      },
      {
        id: "foster",
        word: "foster",
        pos: "verb",
        definition: "to encourage the development of something.",
        example: "Good teachers foster curiosity.",
        synonyms: ["nurture", "promote", "cultivate"],
      },
      {
        id: "hinder",
        word: "hinder",
        pos: "verb",
        definition: "to create difficulties that delay or obstruct.",
        example: "Heavy traffic hindered the rescue effort.",
        synonyms: ["impede", "obstruct", "hamper"],
      },
      {
        id: "illuminate",
        word: "illuminate",
        pos: "verb",
        definition: "to help clarify or explain; to light up.",
        example: "The example illuminated a difficult concept.",
        synonyms: ["clarify", "explain", "light"],
      },
      {
        id: "provoke",
        word: "provoke",
        pos: "verb",
        definition: "to stimulate a reaction or feeling.",
        example: "The essay provoked a lively debate.",
        synonyms: ["incite", "trigger", "stir"],
      },
      {
        id: "reconcile",
        word: "reconcile",
        pos: "verb",
        definition: "to restore friendly relations; to make consistent.",
        example: "It is hard to reconcile the two accounts of the event.",
        synonyms: ["resolve", "harmonize", "settle"],
      },
      {
        id: "yield",
        word: "yield",
        pos: "verb",
        definition: "to produce or provide; to give way.",
        example: "The experiment yielded surprising results.",
        synonyms: ["produce", "give", "generate"],
      },
    ],
  },
  {
    id: "character",
    title: "Describing People",
    description: "Adjectives that capture personality and behavior in narrative passages.",
    words: [
      {
        id: "gregarious",
        word: "gregarious",
        pos: "adjective",
        definition: "fond of company; sociable.",
        example: "Her gregarious nature made her the center of every party.",
        synonyms: ["sociable", "outgoing", "friendly"],
      },
      {
        id: "reticent",
        word: "reticent",
        pos: "adjective",
        definition: "not revealing one's thoughts readily; reserved.",
        example: "He was reticent about his past.",
        synonyms: ["reserved", "withdrawn", "guarded"],
      },
      {
        id: "obstinate",
        word: "obstinate",
        pos: "adjective",
        definition: "stubbornly refusing to change one's mind.",
        example: "The obstinate child refused to eat his vegetables.",
        synonyms: ["stubborn", "headstrong", "inflexible"],
      },
      {
        id: "benevolent",
        word: "benevolent",
        pos: "adjective",
        definition: "kind and generous; well-meaning.",
        example: "The benevolent donor funded the new library.",
        synonyms: ["kind", "generous", "charitable"],
      },
      {
        id: "arrogant",
        word: "arrogant",
        pos: "adjective",
        definition: "having an exaggerated sense of one's own importance.",
        example: "His arrogant remarks offended the whole panel.",
        synonyms: ["haughty", "conceited", "pompous"],
      },
      {
        id: "humble",
        word: "humble",
        pos: "adjective",
        definition: "having a modest view of one's own importance.",
        example: "Despite her fame, she remained humble.",
        synonyms: ["modest", "unassuming", "meek"],
      },
      {
        id: "resilient",
        word: "resilient",
        pos: "adjective",
        definition: "able to recover quickly from difficulties.",
        example: "Children are often remarkably resilient.",
        synonyms: ["tough", "hardy", "adaptable"],
      },
      {
        id: "impulsive",
        word: "impulsive",
        pos: "adjective",
        definition: "acting suddenly without careful thought.",
        example: "Buying the car was an impulsive decision.",
        synonyms: ["rash", "hasty", "spontaneous"],
      },
      {
        id: "astute",
        word: "astute",
        pos: "adjective",
        definition: "having sharp judgment; shrewd.",
        example: "An astute investor, she spotted the trend early.",
        synonyms: ["shrewd", "perceptive", "sharp"],
      },
      {
        id: "compassionate",
        word: "compassionate",
        pos: "adjective",
        definition: "feeling or showing sympathy and concern for others.",
        example: "The nurse was known for her compassionate care.",
        synonyms: ["caring", "sympathetic", "kind"],
      },
      {
        id: "frugal",
        word: "frugal",
        pos: "adjective",
        definition: "careful with money or resources; thrifty.",
        example: "Their frugal habits let them save for a house.",
        synonyms: ["thrifty", "economical", "sparing"],
      },
      {
        id: "eloquent",
        word: "eloquent",
        pos: "adjective",
        definition: "fluent and persuasive in speaking or writing.",
        example: "Her eloquent speech moved the audience to tears.",
        synonyms: ["articulate", "expressive", "fluent"],
      },
    ],
  },
];

export function getDeck(id: string): VocabDeck | undefined {
  return VOCAB_DECKS.find((d) => d.id === id);
}

export const TOTAL_VOCAB_WORDS = VOCAB_DECKS.reduce((n, d) => n + d.words.length, 0);
